n1 = int(input('Digite um número: '))
n2 = int(input('Digite outro número: '))

print(f'\nSoma: {n1 + n2}')
print(f'Subtração: {n1 - n2}')
print(f'Produto: {n1 * n2}')
print(f'Divisão: {n1 / n2 :.2f}')
print(f'Divisão inteira: {n1 // n2}')
print(f'Resto da divisão: {n1 % n2}')
print(f'Potência: {n1 ** n2}')
